@echo off
echo Creando entorno virtual...
python -m venv venv
echo Activando entorno...
call venv\Scripts\activate
echo Instalando dependencias...
pip install -r requirements.txt
echo Listo! Todo instalado.
pause